#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get update -y
sudo apt-get install haproxy -y

#sudo sed -i "s|ENABLED=0|ENABLED=1|g" /etc/default/haproxy
sudo sed -i "\$aENABLED=1\n" /etc/default/haproxy

FRONT_END="\\\nfrontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back\n"

BACK_END="backend http_back\n\tbalance roundrobin\n\tserver 377365-web-01 34.207.120.94:80 check\n\tserver 377365-web-02 52.87.19.84:80 check\n"
sudo sed -i "\$a$FRONT_END\n$BACK_END" /etc/haproxy/haproxy.cfg
sudo service haproxy restart

