#!/usr/bin/env bash
# This script connects to the server using the private key ~/.ssh/school with the user ubuntu.


ssh -i ~/.ssh/school ubuntu@18.204.9.142

# Ensure there is a new line at the end of the file

