#!/usr/bin/env bash
## Function to handle the SIGTERM signal

trapped(){
    echo "I am invincible!!!";
}

trap 'trapped' SIGTERM;

while true; do
    echo "To infinity and beyond";
    sleep 2;
done
