#!/usr/bin/env bash
#displays the username, ID, and home directory path for each user in /etc/passwd

while IFS=":" read -r username uid _ home _; do
    echo "$username:$uid:$home"
done < /etc/passwd
