#!/usr/bin/env bash
#displays "Best School" 10 times, with "Hi" on the 9th iteration

ct=1
while [ $ct -le 10 ]; do
    if [ $ct -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ct=$((ct + 1))
done
