#!/usr/bin/env bash
#displays different messages based on the loop iteration

ct=1
while [ $ct -le 10 ]; do
    if [ $ct -eq 4 ]; then
        echo "bad luck"
    elif [ $ct -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ct=$((ct + 1))
done
