#!/usr/bin/env bash
# displays the content of the current directory in a list format
#showing only the part of the name after the first dash

for file in *; do
    if [ -f "$file" ] && [[ ! "$file" =~ ^\. ]]; then
        echo "${file#*-}"
    fi
done
